#!/usr/bin/env bash

# sbt="$dir/sbt/sbt-launch.jar"
sbt="$SBT_HOME/bin/sbt-launch.jar"


# tweak this line according to your needs
# java $SBT_PROPS -Dsbt.ivy.home="$dir/sbt/repository" -Dsbt.boot.directory="$dir/sbt/boot" -Dsbt.boot.properties="$dir/sbt/sbt.boot.properties" -Xmx512M -jar -Dfile.encoding=UTF8 -Xss1M -XX:+UseShenandoahGC "$sbt" "$@"
java -Xmx512M -jar -Dfile.encoding=UTF8 -Xss1M -XX:+UseShenandoahGC "$sbt" "$@"

